# Demand Types
# Force demands for structural members. Geometry (L, Lb, K, Cb) comes from Member.

abstract type AbstractDemand end

"""Unified demand for framing members (beams, columns, beam-columns)."""
struct MemberDemand{T} <: AbstractDemand
    member_idx::Int
    Pu::T    # axial (+tension, -compression, 0=pure flexure)
    Mux::T   # strong-axis moment
    Muy::T   # weak-axis moment
    Vu::T    # shear
end

# Convenience constructors (the full 5-arg constructor is auto-generated by the struct)

# Beam (flexure + shear only, zero axial)
MemberDemand(idx::Int, Mux::T, Vu::T) where T = MemberDemand{T}(idx, zero(Mux), Mux, zero(Mux), Vu)

# Column (axial with optional moments/shear via kwargs)
function MemberDemand(idx::Int, Pu::T; Mux=zero(Pu), Muy=zero(Pu), Vu=zero(Pu)) where T
    MemberDemand{T}(idx, Pu, Mux, Muy, Vu)
end
